// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Set_Backend.Data;

#nullable disable

namespace Set_Backend.Migrations
{
    [DbContext(typeof(SetGameDbContext))]
    [Migration("20260521084455_Games")]
    partial class Games
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Set_Backend.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Colour")
                        .HasColumnType("integer");

                    b.Property<int>("Filling")
                        .HasColumnType("integer");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("GameId1")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Shape")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = 0,
                            Filling = 0,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 2,
                            Colour = 0,
                            Filling = 0,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 3,
                            Colour = 0,
                            Filling = 0,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 4,
                            Colour = 0,
                            Filling = 1,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 5,
                            Colour = 0,
                            Filling = 1,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 6,
                            Colour = 0,
                            Filling = 1,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 7,
                            Colour = 0,
                            Filling = 2,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 8,
                            Colour = 0,
                            Filling = 2,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 9,
                            Colour = 0,
                            Filling = 2,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 10,
                            Colour = 0,
                            Filling = 0,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 11,
                            Colour = 0,
                            Filling = 0,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 12,
                            Colour = 0,
                            Filling = 0,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 13,
                            Colour = 0,
                            Filling = 1,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 14,
                            Colour = 0,
                            Filling = 1,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 15,
                            Colour = 0,
                            Filling = 1,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 16,
                            Colour = 0,
                            Filling = 2,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 17,
                            Colour = 0,
                            Filling = 2,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 18,
                            Colour = 0,
                            Filling = 2,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 19,
                            Colour = 0,
                            Filling = 0,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 20,
                            Colour = 0,
                            Filling = 0,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 21,
                            Colour = 0,
                            Filling = 0,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 22,
                            Colour = 0,
                            Filling = 1,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 23,
                            Colour = 0,
                            Filling = 1,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 24,
                            Colour = 0,
                            Filling = 1,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 25,
                            Colour = 0,
                            Filling = 2,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 26,
                            Colour = 0,
                            Filling = 2,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 27,
                            Colour = 0,
                            Filling = 2,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 28,
                            Colour = 1,
                            Filling = 0,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 29,
                            Colour = 1,
                            Filling = 0,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 30,
                            Colour = 1,
                            Filling = 0,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 31,
                            Colour = 1,
                            Filling = 1,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 32,
                            Colour = 1,
                            Filling = 1,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 33,
                            Colour = 1,
                            Filling = 1,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 34,
                            Colour = 1,
                            Filling = 2,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 35,
                            Colour = 1,
                            Filling = 2,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 36,
                            Colour = 1,
                            Filling = 2,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 37,
                            Colour = 1,
                            Filling = 0,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 38,
                            Colour = 1,
                            Filling = 0,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 39,
                            Colour = 1,
                            Filling = 0,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 40,
                            Colour = 1,
                            Filling = 1,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 41,
                            Colour = 1,
                            Filling = 1,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 42,
                            Colour = 1,
                            Filling = 1,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 43,
                            Colour = 1,
                            Filling = 2,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 44,
                            Colour = 1,
                            Filling = 2,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 45,
                            Colour = 1,
                            Filling = 2,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 46,
                            Colour = 1,
                            Filling = 0,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 47,
                            Colour = 1,
                            Filling = 0,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 48,
                            Colour = 1,
                            Filling = 0,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 49,
                            Colour = 1,
                            Filling = 1,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 50,
                            Colour = 1,
                            Filling = 1,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 51,
                            Colour = 1,
                            Filling = 1,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 52,
                            Colour = 1,
                            Filling = 2,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 53,
                            Colour = 1,
                            Filling = 2,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 54,
                            Colour = 1,
                            Filling = 2,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 55,
                            Colour = 2,
                            Filling = 0,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 56,
                            Colour = 2,
                            Filling = 0,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 57,
                            Colour = 2,
                            Filling = 0,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 58,
                            Colour = 2,
                            Filling = 1,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 59,
                            Colour = 2,
                            Filling = 1,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 60,
                            Colour = 2,
                            Filling = 1,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 61,
                            Colour = 2,
                            Filling = 2,
                            Number = 1,
                            Shape = 0
                        },
                        new
                        {
                            Id = 62,
                            Colour = 2,
                            Filling = 2,
                            Number = 2,
                            Shape = 0
                        },
                        new
                        {
                            Id = 63,
                            Colour = 2,
                            Filling = 2,
                            Number = 3,
                            Shape = 0
                        },
                        new
                        {
                            Id = 64,
                            Colour = 2,
                            Filling = 0,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 65,
                            Colour = 2,
                            Filling = 0,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 66,
                            Colour = 2,
                            Filling = 0,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 67,
                            Colour = 2,
                            Filling = 1,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 68,
                            Colour = 2,
                            Filling = 1,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 69,
                            Colour = 2,
                            Filling = 1,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 70,
                            Colour = 2,
                            Filling = 2,
                            Number = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 71,
                            Colour = 2,
                            Filling = 2,
                            Number = 2,
                            Shape = 1
                        },
                        new
                        {
                            Id = 72,
                            Colour = 2,
                            Filling = 2,
                            Number = 3,
                            Shape = 1
                        },
                        new
                        {
                            Id = 73,
                            Colour = 2,
                            Filling = 0,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 74,
                            Colour = 2,
                            Filling = 0,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 75,
                            Colour = 2,
                            Filling = 0,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 76,
                            Colour = 2,
                            Filling = 1,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 77,
                            Colour = 2,
                            Filling = 1,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 78,
                            Colour = 2,
                            Filling = 1,
                            Number = 3,
                            Shape = 2
                        },
                        new
                        {
                            Id = 79,
                            Colour = 2,
                            Filling = 2,
                            Number = 1,
                            Shape = 2
                        },
                        new
                        {
                            Id = 80,
                            Colour = 2,
                            Filling = 2,
                            Number = 2,
                            Shape = 2
                        },
                        new
                        {
                            Id = 81,
                            Colour = 2,
                            Filling = 2,
                            Number = 3,
                            Shape = 2
                        });
                });

            modelBuilder.Entity("Set_Backend.Models.FoundSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Card1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Card2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Card3Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Card1Id");

                    b.HasIndex("Card2Id");

                    b.HasIndex("Card3Id");

                    b.HasIndex("GameId");

                    b.ToTable("FoundSets");
                });

            modelBuilder.Entity("Set_Backend.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fails")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hints")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Set_Backend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Set_Backend.Models.Card", b =>
                {
                    b.HasOne("Set_Backend.Models.Game", null)
                        .WithMany("Deck")
                        .HasForeignKey("GameId");

                    b.HasOne("Set_Backend.Models.Game", null)
                        .WithMany("TableCards")
                        .HasForeignKey("GameId1");
                });

            modelBuilder.Entity("Set_Backend.Models.FoundSet", b =>
                {
                    b.HasOne("Set_Backend.Models.Card", "Card1")
                        .WithMany()
                        .HasForeignKey("Card1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Set_Backend.Models.Card", "Card2")
                        .WithMany()
                        .HasForeignKey("Card2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Set_Backend.Models.Card", "Card3")
                        .WithMany()
                        .HasForeignKey("Card3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Set_Backend.Models.Game", "Game")
                        .WithMany("FoundSets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card1");

                    b.Navigation("Card2");

                    b.Navigation("Card3");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Set_Backend.Models.Game", b =>
                {
                    b.HasOne("Set_Backend.Models.Player", null)
                        .WithMany("Game")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Set_Backend.Models.Game", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("FoundSets");

                    b.Navigation("TableCards");
                });

            modelBuilder.Entity("Set_Backend.Models.Player", b =>
                {
                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
